import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import toast, { Toaster } from "react-hot-toast";
import CustomCursor from "@/components/web/shared/CustomCursor";

const manRope = Manrope({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Agency.AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <link rel="icon" href="/images/favicon.ico" sizes="any" />
      <body className={manRope.className}>
        <Toaster />
        {children}
        <CustomCursor />
      </body>
    </html>
  );
}
